site_name: GeekCircle-极客圈
site_url: https://geekcircle.org/
site_description: GeekCircle-极客圈的官方网站，致力于分享原创、有价值的编程技术。
site_author: GeekCircle
nav:
  - 主页: index.md
  - 机器学习Q&A:
    - 1.如何处理特征向量的缺失值: qa/ml/1.md
    - 2.请简要说说一个完整机器学习项目的流程: qa/ml/2.md
    - 3.某超市研究销售记录发现买啤酒的人很大概率也会买尿布，这属于数据挖掘的哪类问题: qa/ml/3.md
    - 4.余弦相似与欧氏距离有什么区别和联系: qa/ml/4.md
    - 5.下面哪个不属于数据的属性类型: qa/ml/5.md
    - 6.监督学习和无监督学习: qa/ml/6.md
    - 7.熵是为消除不确定性所需要获得的信息量，投掷均匀正六面体骰子的熵是: qa/ml/7.md
    - 8.数据清洗与特征处理: qa/ml/8.md
    - 9.猜测这种划分最可能是什么聚类算法的结果: qa/ml/9.md
    - 10.支持向量机(SVM)中的支持向量是什么意思: qa/ml/10.md
    - 11.精确率(precision)和召回率(recall): qa/ml/11.md
    - 12.数据挖掘中如何判断关联规则有效性: qa/ml/12.md
    - 13.朴素贝叶斯分类某个类别概率为0怎么办: qa/ml/13.md
    - 14.决策树: qa/ml/14.md


copyright: 'Copyright &copy; 2016 - 2019 GeekCircle'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

theme:
  language: zh
  name: material
  feature:
    tabs: true
  logo: icon.png
  favicon: icon.png
# extra:
  # disqus: geekcircle
repo_url: https://github.com/geektutu/interview-questions
remote_branch: master
  